"""Fold-Gated Memory: a trace-theoretic agent memory architecture.

Implements the six-layer hierarchy from the trace/fold framework:
    trace (context window) -> storage -> addressability (margin-tracked)
    -> folding (transition-gated) -> operation-memory -> compression
"""
from fgm.core import (
    SOURCE_EXTERNAL,
    SOURCE_TOOL_OUTPUT,
    SOURCE_RETRIEVED_MEMORY,
    SOURCE_INFERENCE,
    SOURCE_SIMULATION,
    SOURCE_FABRICATED,
    SOURCE_OPERATION_RECORD,
    ROUTE_NULL,
    ROUTE_TRACE,
    ROUTE_DURABLE_MEMORY,
    ROUTE_OPERATION_MEMORY,
    ROUTE_CORRECTION_CHAIN,
    ROUTE_QUARANTINE,
    MemoryRecord,
    RetrievalHit,
    RetrievalReport,
    FoldResult,
    OperationRecord,
    CompressionReport,
    MemoryStore,
    MarginRetriever,
    FoldGate,
    OperationMemory,
    Compressor,
    FGMAgent,
    hash_embed,
    default_transition,
)
from fgm.metrics import RegimeEvaluator, RegimeReport
from fgm.inscription import (
    CandidateEvent,
    InscriptionPolicyReport,
    compare_inscription_policies,
    evaluate_inscription_policy,
    make_inscription_utility_fixture,
)
from fgm.correction import (
    CorrectionCase,
    CorrectionNode,
    CorrectionPolicyReport,
    compare_correction_policies,
    evaluate_correction_policy,
    make_correction_chain_fixture,
)
from fgm.residual import (
    RetrievalCandidate,
    RetrievalPolicyReport,
    compare_residual_attention_policies,
    evaluate_residual_attention_policy,
    make_residual_attention_fixture,
)
from fgm.self_index import (
    SelfIndexCase,
    SelfIndexPolicyReport,
    compare_self_index_policies,
    evaluate_self_index_policy,
    make_self_index_fixture,
)
from fgm.coupling import CoupledFieldReport, coupled_field_probe
from fgm.roadmap import (
    make_source_routing_records,
    run_controlled_roadmap_validations,
    write_roadmap_validation_outputs,
)
from fgm.replication import (
    run_controlled_replication,
    write_controlled_replication_outputs,
)
from fgm.real_components import (
    RealComponentReport,
    run_real_embedding_validation,
    run_real_embedding_replication,
    write_real_embedding_replication_output,
    write_real_component_validation_output,
)
from fgm.live_validation import (
    LiveValidationReport,
    run_live_llm_validation,
    run_live_llm_replication,
    write_live_llm_replication_outputs,
    write_live_llm_validation_output,
)
from fgm.live_diagnostics import (
    analyze_live_replication,
    write_live_replication_diagnostics,
)
from fgm.model_comparison import (
    ProviderModelTarget,
    parse_provider_model_target,
    write_live_provider_model_comparison_outputs,
)
from fgm.rerank_validation import (
    run_rerank_boundary_regression,
    write_rerank_boundary_regression_output,
)
from fgm.experiment import Experiment1, ExperimentResult
from fgm.llm import (
    LLMTransition,
    CallStats,
    anthropic_call,
    openai_call,
    echo_call,
    answer_quality_fold_force,
)
from fgm.validation import (
    ValidationRecord,
    apply_route_baseline,
    append_validation_jsonl,
    read_validation_jsonl,
    score_validation_records,
    write_validation_jsonl,
)
from fgm.laundering import (
    InferenceStep,
    LaunderingCase,
    LaunderingPolicyReport,
    LaunderingSeed,
    MultiSeedLaunderingReport,
    compare_laundering_policies,
    compare_laundering_policies_multiseed,
    evaluate_laundering_policy,
    make_extended_adversarial_fixture,
    make_laundering_fixture,
    min_trust_source,
    run_laundering_multiseed,
)
from fgm.source_inference import (
    SOURCE_CLASSES,
    SourceInferenceCase,
    SourceInferenceReport,
    compare_source_inference_policies,
    evaluate_source_inference,
    make_source_inference_fixture,
)

__all__ = [
    "SOURCE_EXTERNAL",
    "SOURCE_TOOL_OUTPUT",
    "SOURCE_RETRIEVED_MEMORY",
    "SOURCE_INFERENCE",
    "SOURCE_SIMULATION",
    "SOURCE_FABRICATED",
    "SOURCE_OPERATION_RECORD",
    "ROUTE_NULL",
    "ROUTE_TRACE",
    "ROUTE_DURABLE_MEMORY",
    "ROUTE_OPERATION_MEMORY",
    "ROUTE_CORRECTION_CHAIN",
    "ROUTE_QUARANTINE",
    "MemoryRecord",
    "RetrievalHit",
    "RetrievalReport",
    "FoldResult",
    "OperationRecord",
    "CompressionReport",
    "MemoryStore",
    "MarginRetriever",
    "FoldGate",
    "OperationMemory",
    "Compressor",
    "FGMAgent",
    "RegimeEvaluator",
    "RegimeReport",
    "CandidateEvent",
    "InscriptionPolicyReport",
    "compare_inscription_policies",
    "evaluate_inscription_policy",
    "make_inscription_utility_fixture",
    "CorrectionCase",
    "CorrectionNode",
    "CorrectionPolicyReport",
    "compare_correction_policies",
    "evaluate_correction_policy",
    "make_correction_chain_fixture",
    "RetrievalCandidate",
    "RetrievalPolicyReport",
    "compare_residual_attention_policies",
    "evaluate_residual_attention_policy",
    "make_residual_attention_fixture",
    "SelfIndexCase",
    "SelfIndexPolicyReport",
    "compare_self_index_policies",
    "evaluate_self_index_policy",
    "make_self_index_fixture",
    "CoupledFieldReport",
    "coupled_field_probe",
    "make_source_routing_records",
    "run_controlled_roadmap_validations",
    "write_roadmap_validation_outputs",
    "run_controlled_replication",
    "write_controlled_replication_outputs",
    "RealComponentReport",
    "run_real_embedding_validation",
    "run_real_embedding_replication",
    "write_real_embedding_replication_output",
    "write_real_component_validation_output",
    "LiveValidationReport",
    "run_live_llm_validation",
    "run_live_llm_replication",
    "write_live_llm_replication_outputs",
    "write_live_llm_validation_output",
    "analyze_live_replication",
    "write_live_replication_diagnostics",
    "ProviderModelTarget",
    "parse_provider_model_target",
    "write_live_provider_model_comparison_outputs",
    "run_rerank_boundary_regression",
    "write_rerank_boundary_regression_output",
    "Experiment1",
    "ExperimentResult",
    "LLMTransition",
    "CallStats",
    "anthropic_call",
    "openai_call",
    "echo_call",
    "answer_quality_fold_force",
    "ValidationRecord",
    "apply_route_baseline",
    "append_validation_jsonl",
    "read_validation_jsonl",
    "score_validation_records",
    "write_validation_jsonl",
    "hash_embed",
    "default_transition",
    "InferenceStep",
    "LaunderingCase",
    "LaunderingPolicyReport",
    "LaunderingSeed",
    "MultiSeedLaunderingReport",
    "compare_laundering_policies",
    "compare_laundering_policies_multiseed",
    "evaluate_laundering_policy",
    "make_extended_adversarial_fixture",
    "make_laundering_fixture",
    "min_trust_source",
    "run_laundering_multiseed",
    "SOURCE_CLASSES",
    "SourceInferenceCase",
    "SourceInferenceReport",
    "compare_source_inference_policies",
    "evaluate_source_inference",
    "make_source_inference_fixture",
]
